# Welcome to Numpy!

## *Introduction*:

*Numpy (Numerical Python) is a library used for scientific computing, linear algebra, data analysis and statistics.*

Numpy has the following features:

1. **High-performance array object**: NumPy arrays are stored in contiguous memory, which makes them much faster to access than Python lists.

2. **Large library of mathematical functions**: NumPy provides a large library of mathematical functions for working with arrays, including basic arithmetic operations, trigonometric functions, and statistical functions.

3. **Linear algebra routines**: NumPy provides a comprehensive set of linear algebra routines for working with arrays, including matrix multiplication, matrix inversion, and eigenvalue decomposition.

4. **Random number generation**: NumPy provides a random number generator that can be used to generate random numbers for a variety of applications.

5. **Integration with other Python libraries**: NumPy can be easily integrated with other Python libraries, such as SciPy and Pandas.

## *Advantages over Lists*:

1. Numpy arrays are much faster than lists.
2. They contain homogeneous elements i.e. all elements of a numpy array are of same data type.
3. Numpy arrays use less memory than lists.
4. They support vectorized operations, while lists don’t.

# Creation of Arrays

## *1D Array*:

In [16]:
import numpy as np

# 1. using array()
print("using array()")
list1 = [1,2,3,5]
a1 = np.array(list1)
print("a1: ",a1)

a2 = np.array([1,2,3,4,5])
print("a2: ",a2)

# 2. using arange()
print("\nusing arange()")
a3 = np.arange(1,10,2) # start, stop, step
print("a3: ",a3)

# 3. using linspace()
print("\nusing linspace()")
a4 = np.linspace(1,10,5) # start, stop, number of elements evenly spaced between start and stop
print("a4: ",a4)

# 4. using zeros()
print("\nusing zeros()")
a5 = np.zeros(5)
print("a5: ",a5)

# 5. using ones()
print("\nusing ones()")
a6 = np.ones(5)
print("a6: ",a6)

# 6. using random.rand()
print("\nusing random.rand()")
a7 = np.random.rand(5) # 5 random numbers between 0 and 1
print("a7: ",a7)

# 7. using random.randn()
print("\nusing random.randn()")
a8 = np.random.randn(5) # 5 random numbers from normal distribution
print("a8: ",a8)

# 8. using random.randint()
print("\nusing random.randint()")
a9 = np.random.randint(1,10,5) # 5 random integers between 1 and 10
print("a9: ",a9)

# 9. using random.seed()
#The np.random.seed(1) function is a useful tool for debugging 
# and for ensuring that your code produces the same results each time it is run.
print("\nusing random.seed()")
np.random.seed(1) # set seed to 1
a10 = np.random.randint(1,10,5) # 5 random integers between 1 and 10
print("a10: ",a10)


np.random.seed(2) # set seed to 2, generate different random numbers for the value 2 of seed
a11 = np.random.randint(1,10,5) # 5 random integers between 1 and 10
print("a11: ",a11)








using array()
a1:  [1 2 3 5]
a2:  [1 2 3 4 5]

using arange()
a3:  [1 3 5 7 9]

using linspace()
a4:  [ 1.    3.25  5.5   7.75 10.  ]

using zeros()
a5:  [0. 0. 0. 0. 0.]

using ones()
a6:  [1. 1. 1. 1. 1.]

using random.rand()
a7:  [0.32053644 0.15442667 0.69886269 0.11995054 0.48517591]

using random.randn()
a8:  [ 1.12527974  0.46937315 -0.01576105  2.00488095  1.6105314 ]

using random.randint()
a9:  [7 2 4 6 9]

using random.seed()
a10:  [6 9 6 1 1]
a11:  [9 9 7 3 9]


## Creation of 2D Arrays

In [2]:
# creation
ar1 = np.array([[1,3,4,5],[2,4,5,7],[5,6,7,2]])
print(ar1)

# reshape
print("\nreshape")
ar2 = ar1.reshape(4,3) # 4 rows x 3 columns
print(ar2)

ar3 = np.array([[1,2,2,2],[2,4,9,7],[5,1,7,1]])

# flatten
print("\nflatten")
ar4 = ar2.flatten()
print(ar4)

# slicing
print("\nslicing")
print(ar1[0:2,1:3]) # 0th and 1st row, 1st and 2nd column


[[1 3 4 5]
 [2 4 5 7]
 [5 6 7 2]]

reshape
[[1 3 4]
 [5 2 4]
 [5 7 5]
 [6 7 2]]

flatten
[1 3 4 5 2 4 5 7 5 6 7 2]

slicing
[[3 4]
 [4 5]]


## Arithmetic Operations on Arrays

In [3]:
# Mathematical operations
print("\nMathematical operations")
print("ar1: ",ar1)
print("ar3: ",ar3)

print("ar1 + ar3: \n",ar1 + ar3) # element wise addition
print("ar1 * ar3: \n",ar1 * ar3) # element wise multiplication
print("ar1 / ar3: \n",ar1 / ar3) # element wise division
print("ar1 ** ar3: \n",ar1 ** ar3) # element wise exponentiation




Mathematical operations
ar1:  [[1 3 4 5]
 [2 4 5 7]
 [5 6 7 2]]
ar3:  [[1 2 2 2]
 [2 4 9 7]
 [5 1 7 1]]
ar1 + ar3: 
 [[ 2  5  6  7]
 [ 4  8 14 14]
 [10  7 14  3]]
ar1 * ar3: 
 [[ 1  6  8 10]
 [ 4 16 45 49]
 [25  6 49  2]]
ar1 / ar3: 
 [[1.         1.5        2.         2.5       ]
 [1.         1.         0.55555556 1.        ]
 [1.         6.         1.         2.        ]]
ar1 ** ar3: 
 [[      1       9      16      25]
 [      4     256 1953125  823543]
 [   3125       6  823543       2]]


# Array Functions

## Basic Functions

In [4]:
# Array Basic functions
print("\nArray functions")
print("ar1: ",ar1)

print("ar1.shape: ",ar1.shape) # number of rows and columns
print("ar1.ndim: ",ar1.ndim) # number of dimensions
print("ar1.size: ",ar1.size) # number of elements
print("ar1.dtype: ",ar1.dtype) # data type
print("ar1.itemsize: ",ar1.itemsize) # size of each element in bytes
print("ar1.data: ",ar1.data) # buffer containing actual elements of the array



Array functions
ar1:  [[1 3 4 5]
 [2 4 5 7]
 [5 6 7 2]]
ar1.shape:  (3, 4)
ar1.ndim:  2
ar1.size:  12
ar1.dtype:  int32
ar1.itemsize:  4
ar1.data:  <memory at 0x000001C8C51D8110>


## Mathematical Functions

In [5]:
# Math functions
print("\nMath functions")
print("ar1: ",ar1)

print("ar1.sum(): ",ar1.sum()) # sum of all elements
print("ar1.sum(axis=0): ",ar1.sum(axis=0)) # sum of each column
print("ar1.sum(axis=1): ",ar1.sum(axis=1)) # sum of each row

print("ar1.min(): ",ar1.min()) # minimum of all elements
print("ar1.max(): ",ar1.max()) # maximum of all elements

print("ar1.mean(): ",ar1.mean()) # mean of all elements
#print("ar1.mode(): ",ar1.mode()) 
#print("ar1.median(): ",ar1.median()) 
print("ar1.std(): ",ar1.std()) # standard deviation of all elements
print("ar1.var(): ",ar1.var()) # variance of all elements




Math functions
ar1:  [[1 3 4 5]
 [2 4 5 7]
 [5 6 7 2]]
ar1.sum():  51
ar1.sum(axis=0):  [ 8 13 16 14]
ar1.sum(axis=1):  [13 18 20]
ar1.min():  1
ar1.max():  7
ar1.mean():  4.25
ar1.std():  1.8763883748662837
ar1.var():  3.5208333333333335


# Array Manipulation

contains resize, append, transpose, concatenate, fill.

In [6]:
# Array Manipulation
print("\nArray Manipulation")
ar1 = np.array([[1,3,4,5],[2,4,5,7],[5,6,7,2]])

#resize
print("\nresize")
ar1.resize(2,6)
print(ar1)

#append
print("\nappend row")
ar1 = np.append(ar1,[[1,2,3,4,5,6]],axis=0) # append row
print(ar1)

print("\nappend column")
ar1 = np.append(ar1,[[1],[2],[3]],axis=1) # append column
print(ar1)

#transpose
print("\ntranspose")
ar1 = ar1.transpose()
print(ar1)



Array Manipulation

resize
[[1 3 4 5 2 4]
 [5 7 5 6 7 2]]

append row
[[1 3 4 5 2 4]
 [5 7 5 6 7 2]
 [1 2 3 4 5 6]]

append column
[[1 3 4 5 2 4 1]
 [5 7 5 6 7 2 2]
 [1 2 3 4 5 6 3]]

transpose
[[1 5 1]
 [3 7 2]
 [4 5 3]
 [5 6 4]
 [2 7 5]
 [4 2 6]
 [1 2 3]]


In [7]:
#concatenate
print("\nconcatenate row wise")
ar1 = np.array([[1,3,4,5],[2,4,5,7],[5,6,7,2]])
ar2 = np.array([[1,2,2,2],[2,4,9,7],[5,1,7,1]])
ar3 = np.concatenate((ar1,ar2),axis=0) # concatenate row wise
print(ar3)

print("\nconcatenate column wise")
ar4 = np.concatenate((ar1,ar2),axis=1) # concatenate column wise
print(ar4)

#fill with a constant value
print("\nfill with a constant value")
ar1.fill(2)
print(ar1)


concatenate row wise
[[1 3 4 5]
 [2 4 5 7]
 [5 6 7 2]
 [1 2 2 2]
 [2 4 9 7]
 [5 1 7 1]]

concatenate column wise
[[1 3 4 5 1 2 2 2]
 [2 4 5 7 2 4 9 7]
 [5 6 7 2 5 1 7 1]]

fill with a constant value
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


# Splitting Arrays

contains split, hsplit, vsplit.

In [8]:
# spliting arrays using
# 1. hsplit()
print("\nhsplit")
ar1 = np.array([[1,3,4,5],[2,4,5,7],[5,6,7,2]])
ar2 = np.hsplit(ar1,2) # split into 2 equal parts column wise
print(ar2)
print("\n")

# 2. vsplit()
print("\nvsplit")
ar1 = np.array([[1,3,4,5],[2,4,5,7],[5,6,7,2]])
ar2 = np.vsplit(ar1,3) # split into 3 equal parts row wise
print(ar2)
print("\n")


# 4. split()
print("\nsplit")
ar1 = np.array([[1,3,4,5],[2,4,5,7],[5,6,7,2]])
ar2 = np.split(ar1,3) # split into 3 equal parts row wise
print(ar2)



hsplit
[array([[1, 3],
       [2, 4],
       [5, 6]]), array([[4, 5],
       [5, 7],
       [7, 2]])]



vsplit
[array([[1, 3, 4, 5]]), array([[2, 4, 5, 7]]), array([[5, 6, 7, 2]])]



split
[array([[1, 3, 4, 5]]), array([[2, 4, 5, 7]]), array([[5, 6, 7, 2]])]
